services:
  app: 
    build:
      target: node_dev
    labels:
      - "traefik.http.routers.blitz-task-client.rule=Host(`note-snap.docker.localhost`)"
      - "traefik.http.routers.blitz-task-client-http.rule=Host(`note-snap.docker.localhost`)"

    # - "traefik.http.routers.note-snap-db.rule=Host(`db.note-snap.docker.localhost`)"
    # - "traefik.http.routers.note-snap-db.entrypoints=web"
    # - "traefik.http.services.note-snap-db.loadbalancer.server.port=3500"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - traefik
    ports:
      - 3500:3000
      - 9500:9500
    environment:
      - SMTP_PORT=1025
      - SMTP_HOST=mailer
      - SMTP_SECURE=false
      - EMAIL_ENABLED=true
      - EMAIL_SERVICE=smtp
    volumes:
      - .:/app
      - /app/node_modules

  database:
    ports:
      - "5432"
    networks:
      - traefik

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`db.note-snap.docker.localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - traefik
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database

networks:
  traefik:
    external: true

volumes:
  pgadmin_data: